using System.ComponentModel;

namespace ForgeViewer.NET.Models
{
    public enum ViewerEvent
    {
        [Description("aggregateFitToView")]
        AggregateFitToViewEvent,
        [Description("aggregateIsolation")]
        AggregateIsolationChangedEvent,
        [Description("aggregateSelection")]
        AggregateSelectionChangedEvent,
        [Description("animationReady")]
        AnimationReadyEvent,
        [Description("cameraChanged")]
        CameraChangeEvent,
        [Description("cameraTransitionCompleted")]
        CameraTransitionCompleted,
        [Description("cutplanesChanged")]
        CutPlanesChangeEvent,
        [Description("cancelLeafletScreenshot")]
        CancelLeafletScreenshot,
        [Description("escape")]
        EscapeEvent,
        [Description("explodeChanged")]
        ExplodeChangeEvent,
        [Description("extensionLoaded")]
        ExtensionLoadedEvent,
        [Description("extensionUnloaded")]
        ExtensionUnloadedEvent,
        [Description("finalFrameRenderedChanged")]
        FinalFrameRenderedChangedEvent,
        [Description("fitToView")]
        FitToViewEvent,
        [Description("fragmentsLoaded")]
        FragmentsLoadedEvent,
        [Description("fullscreenMode")]
        FullscreenModeEvent,
        [Description("geometryLoaded")]
        GeometryLoadedEvent,
        [Description("geometryDownloadComplete")]
        GeometryDownloadCompleteEvent,
        [Description("hide")]
        HideEvent,
        [Description("hyperlink")]
        HyperlinkEvent,
        [Description("isolate")]
        IsolateEvent,
        [Description("layerVisibilityChanged")]
        LayerVisibilityChangedEvent,
        [Description("loadGeometry")]
        LoadGeometryEvent,
        [Description("loadMissingGeometry")]
        LoadMissingGeometry,
        [Description("modelAdded")]
        ModelAddedEvent,
        [Description("modelRootLoaded")]
        ModelRootLoadedEvent,
        [Description("modelRemoved")]
        ModelRemovedEvent,
        [Description("modelLayersLoaded")]
        ModelLayersLoadedEvent,
        [Description("modelUnloaded")]
        ModelUnloadedEvent,
        [Description("navigationModeChanged")]
        NavigationModeChangedEvent,
        [Description("objectTreeCreated")]
        ObjectTreeCreatedEvent,
        [Description("objectTreeUnavailable")]
        ObjectTreeUnavailableEvent,
        [Description("prefChanged")]
        PrefChangedEvent,
        [Description("prefReset")]
        PrefResetEvent,
        [Description("progressUpdate")]
        ProgressUpdateEvent,
        [Description("renderFirstPixel")]
        RenderFirstPixel,
        [Description("renderOptionChanged")]
        RenderOptionChangedEvent,
        [Description("renderPresented")]
        RenderPresentedEvent,
        [Description("reset")]
        ResetEvent,
        [Description("restoreDefaultSettings")]
        RestoreDefaultSettingsEvent,
        [Description("selection")]
        [EventResponse(typeof(Selection))]
        SelectionChangedEvent,
        [Description("show")]
        ShowEvent,
        [Description("texturesLoaded")]
        TexturesLoadedEvent,
        [Description("toolChanged")]
        ToolChangeEvent,
        [Description("toolbarCreated")]
        ToolbarCreatedEvent,
        [Description("viewerInitialized")]
        ViewerInitialized,
        [Description("viewerResize")]
        [EventResponse(typeof(Dimension))]
        ViewerResizeEvent,
        [Description("viewerStateRestored")]
        ViewerStateRestoredEvent,
        [Description("viewerUninitialized")]
        ViewerUninitialized,
        [Description("webGlContextLost")]
        WebGlContextLostEvent
    }
}